### ISSUE TITLE
Incremental or full config update

### ISSUE THREAD

**Issue by mdan1eli** [articulate/biplane#1]
Hello, pretty much what i was looking for, as I need to automate deployment of my API via Kong and I don't need a full API developer portal at the moment (that means Gelato is not yet of interest and I still want headless automation).  I will look into much more detail.  A quick question, is API configuration full or can be incremental? 

Thanks

**Comment by plukevdh** [comment]
Hey there. Glad this fits a good niche for folks beyond us! Thanks for sharing.

The config updates are incremental. It does a diff of the config with what currently exists in the Kong instance and then updates things that are modified, removed or added only. You can do a "dry run" of sorts via the `diff` command: `biplane diff --url <kong uri> my-config.yml`

Only the things reported back will be modified. If no changes exist, nothing will be executed. Does that answer what you are asking?
