### ISSUE TITLE
Global Plugins Support

### ISSUE THREAD

**Issue by peter-evans** [articulate/biplane#15]
Would be great to have global plugins support. According to the Kong documentation, many plugins can now be set globally for all APIs. For example:

https://getkong.org/plugins/request-size-limiting/
> You can also apply it for every API using the http://kong:8001/plugins/ endpoint. Read the Plugin Reference for more information.

It's not a big deal, but adding the same plugin to every API just creates unnecessary clutter in the config yaml file.

**Comment by plukevdh** [comment]
Love this idea, and we could definitely utilize this as well. Right now the more urgent issue is to rebuild this CLI in a language other than Crystal. Crystal has caused us a lot of problems so that idea will likely wait for the port. Thanks for the suggestion!

**Comment by peter-evans** [comment]
Great. Looking forward to the port.
Thank you for biplane. I've found it very useful.
