### ISSUE TITLE
Docker containers immediately exit

### ISSUE THREAD

**Issue by Boggin** [articulate/biplane#18]
I've pulled the latest image (and the 1.4.0 image as a double-check) and created containers from them. 

I can't run them, however, as they immediately exit. I don't know how to use dockerized Biplane. Maybe it's broken. Could the README have some details on the expected usage of the container, please?

**Comment by plukevdh** [comment]
@Boggin We can definitely add docs to the README, but if you check the Dockerfile, you'll find it's pointed at the `biplane` executable, so you'd need to provide parameters to actually _do_ something.

Try a `docker run --rm -it articulate/biplane -h`

It's not broken, it just doesn't _do_ anything unless you give it commands.
