### ISSUE TITLE
cast to Int64 error when running biplane on ubuntu precise 64

### ISSUE THREAD

**Issue by mdan1eli** [articulate/biplane#3]
Hello,
I have downloaded (1.2.2) and built from source on precise 64 the tool.  When I run any command, for example _biplane config_  I get an error like the one below.  On which Linux version are you running?

cast to Int64 failed (TypeCastError)
[4309115] ???
[4345512] main +40
[140482219730797] __libc_start_main +237
[4281689] ???

**Comment by plukevdh** [comment]
Hey there @mdan1eli. Thanks for filing this. 

Can you provide a minimal example config that reproduces this issue? We have a prebuilt docker image we use with `ubuntu:latest` which I believe is [16.04](https://hub.docker.com/_/ubuntu/). I am not sure if this is 64 or not.

**Comment by mdan1eli** [comment]
I was running precise 64 bit in a vagrant with virtual box.  Now I have moved to a Linux box with 16.04 and installed with dependent libraries and it works.  Just as a minor side note for documentation, it looks like the _--no-https_ flag is needed if running admin api on http (but of course I am going to loop admin api via kong and ssl)

**Comment by mdan1eli** [comment]
I have reproduced the error when i use the config command to store my local configuration.  If I remove the .biplane file it works again.

**Comment by plukevdh** [comment]
That config issue is a separate problem. Unfortunately crystal's default error reporting is kinda ugly and I'm not yet done catching all the things that might happen. I'll open a separate issue for this.

**Comment by plukevdh** [comment]
Also of note, the `--no-https` is currently backwards. A change in the CLI caused that flag to switch improperly. A fix is already added but Travis is failing to build due to breaking changes in the latest Crystal release. Should have a fix later this afternoon.
